# docker-compose.yml

version: '3.8'
services:

  auth-db:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    volumes:
      - auth-db:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  auth-db:
